name: complex flow

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date
  windows:
    runs-on: windows-latest
    steps:
      - run: date
  mac:
    runs-on: macos-latest
    steps:
      - run: date
  mac2:
    runs-on: macos-latest
    needs: [ubuntu, windows, mac]
    steps:
      - run: date
